#!/bin/python3

import os
import sys

update_directory = '.'
if len(sys.argv) > 1:
    update_directory = sys.argv[1]

with open(update_directory+'/README.md', 'w') as readme:
    readme.write('# Directory of '+update_directory[1:]+':\n')
    readme.write('## Subdirectories:\n')
    readme.write('- [./](./)\n')
    if not os.path.exists(update_directory+'/.git'):
        readme.write('- [../](../)\n')
    files = ""
    for file in os.scandir(update_directory):
        if not file.name.startswith('.') and not file.name == 'README.md':
            if file.is_dir():
                    readme.write('- ['+file.name+']('+file.name+')\n')
                    os.system(sys.argv[0]+' '+file.path)
            elif file.is_file():
                files = files + '- ['+file.name+']('+file.name+')\n'
    readme.write('## Files:\n')
    readme.write(files)
